######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 22 19:37:16 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .\

# Input
HEADERS += System.h
SOURCES += main.cpp System.cpp


include($$(Function_Data_Path)/QT_Enviroment.inc)

