MODULES      += EIGEN3 OPENCV
DEFINES      += 
COMPILEFLAGS += -msse4.2 -DNDEBUG -m64 -pipe -std=c++11 -O3 -O2 -Wall -W -D_REENTRANT -DENABLE_SSE -DHAS_DVO -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED

