TOPDIR 	?= ..
MAKE_TYPE =bin
LIB_PREFIX=
BUILD_PATH=$(TOPDIR)/build/$(HereFolderName)

COMPILEFLAGS= $(ALL_CFLAGS)
LINKFLAGS   = $(ALL_LDFLAGS)
BIN_PATH   ?= $(TOPDIR)
OUTPUT      = Map2DFusion
EXEEXT      =  

include $(TOPDIR)/scripts/make.conf


